### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by kedare** [aristanetworks/goeapi#38]
Hello.

I have been trying to connect using both Connect and ConnectTo without success.

- I do have the .eapi.conf setup properly
- Using the Python client works fine without any change.

When using the ConnectFor, I see  that Connections is set to `[]`, and I get the following error : `panic: Connection profile not found in config` (the same .eapi.conf at the same location works fine with pyeapi)

When using the Connect, I don't get any error, but the node variable is empty, it looks like it's not trying to connect at all ?

Any idea of what could be the issue ?

Thank you.

**Comment by cheynearista** [comment]
@kedare Can you include your .eapi.conf? It's not guaranteed that goeapi will parse the same .eapi.conf as pyeapi will. The two repos are not totally in sync WRT features/abilities, etc.

**Comment by kedare** [comment]
There you have, the user is set like this because it's a proxy that will forward transparently the connection to the device (Didn't had any issues with the Python API so far, it should be completely transparent)

```
[connection:dc1-51a-a72-aaa]
host: net-prod.bastions.xxx.net
transport: https
username: myproxyuser@mydeviceuser@dc1-51a-a72-aaa
password: my-password
port: 8443
```

**Comment by TimRots** [comment]
> ```
> [connection:dc1-51a-a72-aaa]
> host: net-prod.bastions.xxx.net
> transport: https
>> username: myproxyuser@mydeviceuser@dc1-51a-a72-aaa
> password: my-password
> port: 8443
> ```
your config will result in url https://myproxyuser@mydeviceuser@dc1-51a-a72-aaa:my-password@net-prod.bastions.xxx.net:8443/ , which silently fails.

Change the @ symbol in your username to something else and you will be good to Go

**Comment by kedare** [comment]
I can't change it in my case, this is used by the proxy to connect to the end device and map the proxy user to the device user, we don't have direct eAPI access to the devices.

This is compliant with standard http so maybe there is an issue somewhere it the client (because it work fine everywhere else we tried it)

**Comment by cheynearista** [comment]
I have a fix for this in branch issue-38. It should percent-encode (or URL encode) to form a url like:
```
http://myproxyuser%40mydeviceuser%40dc1-51a-a72-aaa:admin@10.81.108.84:80/command-api
```
I'll see if I can't get this committed tomorrow. Sorry for the delay.

**Comment by kedare** [comment]
No problem :)
Thank you.

**Comment by cheynearista** [comment]
I think this should be resolved now although I've not fully tested it. :-)
Let me know if it still persists to give issues.
