### ISSUE TITLE
Have Connect() return Node

### ISSUE THREAD

**Issue by cheynearista** [aristanetworks/goeapi#9]
Currently Connect() returns EapiConnectionEntity. Brought to attention that this would be be easier to use (for users not using ConnectTo()) if we return Node. Need to look into and address.

**Comment by gavmckee80** [comment]
@cheynearista This would be very useful .  I'd like to connect to devices directly without using a configuration file .  My use case can take device details directly from a postgres db call.  I think the api being so tightly bound to the configuration file right now is not a great thing.

**Comment by cheynearista** [comment]
@gavmckee80 I agree. I've been dragging my feet on this for a while. I've made the change to Connect to return the Node reference.

**Comment by gavmckee80** [comment]
@cheynearista thanks for addressing this
